services:
  zookeeper:
    image: fit3182/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"

  pyspark:
    image: fit3182/pyspark
    ports:
      - "${JUPYTER_PORT}:8888"
      - "${SPARKUI_PORT}:4040"
      - "${SPARK_MASTER_PORT}:7077"
      - "8080:8080"
      - "${SPARK_DRIVER_PORT}:39000"
      - "${SPARK_BLOCK_MANAGER_PORT}:39001"
    volumes:
      - ${PROJECT_ROOT}:/home/student
      - /mnt/shared:/mnt/shared
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root
    user: "root"
    environment:
      SPARK_MASTER_URL: ${SPARK_MASTER_URL}